[package]
name = "editor_as_plugin"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.2"
space_editor = { git = "https://github.com/rewin123/space_editor", branch = "v0.6" }

[lints]
workspace = true
